### ISSUE TITLE
PlusLabNLP / DEGREE  list out of range

### ISSUE THREAD

**Issue by fireiceli** [simon-p-j-r/Deep_Learning#2]
in DEGREE , I'm having the same  issue about dev and test,  how did you fix it?

**Comment by simon-p-j-r** [comment]
可以试着改一下transformers的版本。
本质上引起这个问题是因为预测出来的结果和模板之间有差别，导致正则表达式抽取的时候报错。

**Comment by fireiceli** [comment]
了解了，感谢解答。




nihility
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "simon-p-j-r/Deep_Learning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月13日(星期一) 中午11:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [simon-p-j-r/Deep_Learning] PlusLabNLP / DEGREE  list out of range (Issue #2)





 
可以试着改一下transformers的版本。
 本质上引起这个问题是因为预测出来的结果和模板之间有差别，导致正则表达式抽取的时候报错。
